spring:
  datasource:
    # 为了 docker 设置 MySQL 地址准备
    host: 127.0.0.1
    # 连接 MySQL
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${spring.datasource.host}:3306/osc_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: 123456

  # 连接 Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456789

  # 连接 MongoDB
  data:
    mongodb:
      host: 127.0.0.1
      # 无密码
      # uri: mongodb://${spring.data.mongodb.host}:27017/osc_db
      # 有密码（name：用户名 / password：密码）
      uri: mongodb://zwc:123456@${spring.data.mongodb.host}:27017/osc_db
