# 端口
server:
  port: 8081

spring:
  application:
    # 应用名称
    name: log-service

  datasource:
    # 为了 docker 设置 MySQL 地址准备
    host: 127.0.0.1
    # 连接 MySQL
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${spring.datasource.host}:3306/osc_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: 123456

  # 连接 Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456789

  # 连接 MongoDB
  data:
    mongodb:
      host: 127.0.0.1
      # 无密码
      # uri: mongodb://localhost:27017/osc_db
      # 有密码（name：用户名 / password：密码）
      uri: mongodb://zwc:123456@${spring.data.mongodb.host}:27017/osc_db

  # 配置 Flyway
  flyway:
    ## sql 脚本的位置，默认为 classpath:db/migration。可手动指定
    locations: classpath:db/zwc
    ## 开启，默认开启
    enabled: true

  # 配置链路中心地址
  zipkin:
    # 为了 docker 设置 zipkin 服务器地址准备
    host: 127.0.0.1
    # 指定了 zipkin 服务器的地址
    base-url: http://${spring.zipkin.host}:9411
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1.0

eureka:
  server:
    # 为了 docker 设置注册中心地址准备
    host: 127.0.0.1
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.server.host}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        # 开启监控端点
        include: hystrix.stream

# 打印 sql 日志
logging:
  level:
    com.zwc.base.mapper: debug
